      REAL*8  QTCR    ! Supplemental variable   1
      EQUIVALENCE ( QTCR  ,  SPTACS(  45312 )  )
      REAL*8  QREF    ! Supplemental variable   2
      EQUIVALENCE ( QREF  ,  SPTACS(  45313 )  )
      REAL*8  TRAB    ! Supplemental variable   3
      EQUIVALENCE ( TRAB  ,  SPTACS(  45314 )  )
      REAL*8  TRBC    ! Supplemental variable   4
      EQUIVALENCE ( TRBC  ,  SPTACS(  45315 )  )
      REAL*8  TRCA    ! Supplemental variable   5
      EQUIVALENCE ( TRCA  ,  SPTACS(  45316 )  )
      REAL*8  TABX    ! Supplemental variable   6
      EQUIVALENCE ( TABX  ,  SPTACS(  45317 )  )
      REAL*8  TBCX    ! Supplemental variable   7
      EQUIVALENCE ( TBCX  ,  SPTACS(  45318 )  )
      REAL*8  TCAX    ! Supplemental variable   8
      EQUIVALENCE ( TCAX  ,  SPTACS(  45319 )  )
      REAL*8  TXNAB   ! Supplemental   device   9
      EQUIVALENCE ( TXNAB ,  SPTACS(  45320 )  )
      REAL*8  TXNBC   ! Supplemental   device  10
      EQUIVALENCE ( TXNBC ,  SPTACS(  45321 )  )
      REAL*8  TXNCA   ! Supplemental   device  11
      EQUIVALENCE ( TXNCA ,  SPTACS(  45322 )  )
      REAL*8  FAB1    ! Supplemental   device  12
      EQUIVALENCE ( FAB1  ,  SPTACS(  45323 )  )
      REAL*8  FAB2    ! Supplemental   device  13
      EQUIVALENCE ( FAB2  ,  SPTACS(  45324 )  )
      REAL*8  FIAB1   ! Supplemental   device  14
      EQUIVALENCE ( FIAB1 ,  SPTACS(  45325 )  )
      REAL*8  FIAB2   ! Supplemental   device  15
      EQUIVALENCE ( FIAB2 ,  SPTACS(  45326 )  )
      REAL*8  DELIN   ! Supplemental variable  16
      EQUIVALENCE ( DELIN ,  SPTACS(  45327 )  )
      REAL*8  FBC1    ! Supplemental   device  17
      EQUIVALENCE ( FBC1  ,  SPTACS(  45328 )  )
      REAL*8  FBC2    ! Supplemental   device  18
      EQUIVALENCE ( FBC2  ,  SPTACS(  45329 )  )
      REAL*8  FIBC1   ! Supplemental   device  19
      EQUIVALENCE ( FIBC1 ,  SPTACS(  45330 )  )
      REAL*8  FIBC2   ! Supplemental   device  20
      EQUIVALENCE ( FIBC2 ,  SPTACS(  45331 )  )
      REAL*8  FCA1    ! Supplemental   device  21
      EQUIVALENCE ( FCA1  ,  SPTACS(  45332 )  )
      REAL*8  FCA2    ! Supplemental   device  22
      EQUIVALENCE ( FCA2  ,  SPTACS(  45333 )  )
      REAL*8  FICA1   ! Supplemental   device  23
      EQUIVALENCE ( FICA1 ,  SPTACS(  45334 )  )
      REAL*8  FICA2   ! Supplemental   device  24
      EQUIVALENCE ( FICA2 ,  SPTACS(  45335 )  )
      REAL*8  TRIA    ! Supplemental   device  25
      EQUIVALENCE ( TRIA  ,  SPTACS(  45336 )  )
      REAL*8  TRVA    ! Supplemental   device  26
      EQUIVALENCE ( TRVA  ,  SPTACS(  45337 )  )
      REAL*8  QINA    ! Supplemental variable  27
      EQUIVALENCE ( QINA  ,  SPTACS(  45338 )  )
      REAL*8  TRIB    ! Supplemental   device  28
      EQUIVALENCE ( TRIB  ,  SPTACS(  45339 )  )
      REAL*8  TRVB    ! Supplemental   device  29
      EQUIVALENCE ( TRVB  ,  SPTACS(  45340 )  )
      REAL*8  QINB    ! Supplemental variable  30
      EQUIVALENCE ( QINB  ,  SPTACS(  45341 )  )
      REAL*8  TRIC    ! Supplemental   device  31
      EQUIVALENCE ( TRIC  ,  SPTACS(  45342 )  )
      REAL*8  TRVC    ! Supplemental   device  32
      EQUIVALENCE ( TRVC  ,  SPTACS(  45343 )  )
      REAL*8  QINC    ! Supplemental variable  33
      EQUIVALENCE ( QINC  ,  SPTACS(  45344 )  )
      REAL*8  DLA1    ! Supplemental variable  34
      EQUIVALENCE ( DLA1  ,  SPTACS(  45345 )  )
      REAL*8  REOAB   ! Supplemental   device  35
      EQUIVALENCE ( REOAB ,  SPTACS(  45346 )  )
      REAL*8  DELYAA  ! Supplemental   device  36
      EQUIVALENCE ( DELYAA,  SPTACS(  45347 )  )
      REAL*8  DELYA   ! Supplemental variable  37
      EQUIVALENCE ( DELYA ,  SPTACS(  45348 )  )
      REAL*8  DLB1    ! Supplemental variable  38
      EQUIVALENCE ( DLB1  ,  SPTACS(  45349 )  )
      REAL*8  REOBC   ! Supplemental   device  39
      EQUIVALENCE ( REOBC ,  SPTACS(  45350 )  )
      REAL*8  DELYBB  ! Supplemental   device  40
      EQUIVALENCE ( DELYBB,  SPTACS(  45351 )  )
      REAL*8  DELYB   ! Supplemental variable  41
      EQUIVALENCE ( DELYB ,  SPTACS(  45352 )  )
      REAL*8  DLC1    ! Supplemental variable  42
      EQUIVALENCE ( DLC1  ,  SPTACS(  45353 )  )
      REAL*8  REOCA   ! Supplemental   device  43
      EQUIVALENCE ( REOCA ,  SPTACS(  45354 )  )
      REAL*8  DELYCC  ! Supplemental   device  44
      EQUIVALENCE ( DELYCC,  SPTACS(  45355 )  )
      REAL*8  DELYC   ! Supplemental variable  45
      EQUIVALENCE ( DELYC ,  SPTACS(  45356 )  )
C      ================  End supplementals.  Begin S-blocks
      REAL*8  INREAB  ! Output of S-block  1
      EQUIVALENCE ( INREAB,  SPTACS(  44645 )  )
      REAL*8  DELAB   ! Output of S-block  2
      EQUIVALENCE ( DELAB ,  SPTACS(  44646 )  )
      REAL*8  INREBC  ! Output of S-block  3
      EQUIVALENCE ( INREBC,  SPTACS(  44647 )  )
      REAL*8  DELBC   ! Output of S-block  4
      EQUIVALENCE ( DELBC ,  SPTACS(  44648 )  )
      REAL*8  INRECA  ! Output of S-block  5
      EQUIVALENCE ( INRECA,  SPTACS(  44649 )  )
      REAL*8  DELCA   ! Output of S-block  6
      EQUIVALENCE ( DELCA ,  SPTACS(  44650 )  )
      REAL*8  QINCRC  ! Output of S-block  7
      EQUIVALENCE ( QINCRC,  SPTACS(  44651 )  )
      REAL*8  ERRQC   ! Output of S-block  8
      EQUIVALENCE ( ERRQC ,  SPTACS(  44652 )  )
      REAL*8  QINCRB  ! Output of S-block  9
      EQUIVALENCE ( QINCRB,  SPTACS(  44653 )  )
      REAL*8  ERRQB   ! Output of S-block 10
      EQUIVALENCE ( ERRQB ,  SPTACS(  44654 )  )
      REAL*8  QINCRA  ! Output of S-block 11
      EQUIVALENCE ( QINCRA,  SPTACS(  44655 )  )
      REAL*8  ERRQA   ! Output of S-block 12
      EQUIVALENCE ( ERRQA ,  SPTACS(  44656 )  )
      REAL*8  QRNEW   ! Output of S-block 13
      EQUIVALENCE ( QRNEW ,  SPTACS(  44657 )  )
      REAL*8  DVQ     ! Output of S-block 14
      EQUIVALENCE ( DVQ   ,  SPTACS(  44658 )  )
      REAL*8  VLLAVG  ! Output of S-block 15
      EQUIVALENCE ( VLLAVG,  SPTACS(  44659 )  )
C      ================  End S-blocks;  Begin all sources:
      REAL*8  TIMEX   ! TACS source  1
      EQUIVALENCE ( TIMEX ,  SPTACS(  44660 )  )
      REAL*8  FREQHZ  ! TACS source  4
      EQUIVALENCE ( FREQHZ,  SPTACS(  44663 )  )
      REAL*8  OMEGAR  ! TACS source  5
      EQUIVALENCE ( OMEGAR,  SPTACS(  44664 )  )
      REAL*8  ZERO    ! TACS source  6
      EQUIVALENCE ( ZERO  ,  SPTACS(  44665 )  )
      REAL*8  PLUS1   ! TACS source  7
      EQUIVALENCE ( PLUS1 ,  SPTACS(  44666 )  )
      REAL*8  MINUS1  ! TACS source  8
      EQUIVALENCE ( MINUS1,  SPTACS(  44667 )  )
      REAL*8  INFNTY  ! TACS source 10
      EQUIVALENCE ( INFNTY,  SPTACS(  44669 )  )
      REAL*8  PI      ! TACS source 11
      EQUIVALENCE ( PI    ,  SPTACS(  44670 )  )
      REAL*8  VREFD   ! TACS source 12
      EQUIVALENCE ( VREFD ,  SPTACS(  44671 )  )
      REAL*8  TRSA    ! TACS source 13
      EQUIVALENCE ( TRSA  ,  SPTACS(  44672 )  )
      REAL*8  TRSB    ! TACS source 14
      EQUIVALENCE ( TRSB  ,  SPTACS(  44673 )  )
      REAL*8  TRSC    ! TACS source 15
      EQUIVALENCE ( TRSC  ,  SPTACS(  44674 )  )
      REAL*8  RMAB    ! TACS source 16
      EQUIVALENCE ( RMAB  ,  SPTACS(  44675 )  )
      REAL*8  RMBC    ! TACS source 17
      EQUIVALENCE ( RMBC  ,  SPTACS(  44676 )  )
      REAL*8  RMCA    ! TACS source 18
      EQUIVALENCE ( RMCA  ,  SPTACS(  44677 )  )
      REAL*8  TRXA    ! TACS source 19
      EQUIVALENCE ( TRXA  ,  SPTACS(  44678 )  )
      REAL*8  TRXB    ! TACS source 20
      EQUIVALENCE ( TRXB  ,  SPTACS(  44679 )  )
      REAL*8  TRXC    ! TACS source 21
      EQUIVALENCE ( TRXC  ,  SPTACS(  44680 )  )
      REAL*8  FRLA    ! TACS source 22
      EQUIVALENCE ( FRLA  ,  SPTACS(  44681 )  )
      REAL*8  FRLB    ! TACS source 23
      EQUIVALENCE ( FRLB  ,  SPTACS(  44682 )  )
      REAL*8  FRLC    ! TACS source 24
      EQUIVALENCE ( FRLC  ,  SPTACS(  44683 )  )
